database: false
entry-exit-messages: true
transitzones:
  enabled: true
pvp:
  enabled: true
mob_spawns:
  enabled: true
  only-above-sea-level: true
  blocked-reasons:
   - DEFAULT
   - LIGHTNING
   - SPAWNER_EGG
   - SPAWNER
   - SLIME_SPLIT
   - VILLAGE_INVASION
   - NATURAL
  blocked-types:
   - BLAZE
   - CAVE_SPIDER
   - CREEPER
   - ENDER_DRAGON
   - ENDERMAN
   - GHAST
   - GIANT
   - MAGMA_CUBE
   - PIG_ZOMBIE
   - SILVERFISH
   - SKELETON
   - SLIME
   - SPIDER
   - WITCH
   - WITHER
   - ZOMBIE
