main: ${project.main}
author: ${project.authors}
version: ${project.version}
name: ${project.name}
depend: [GriefPreventionTNG]

commands:
  gpsetmessage:
    usage: /<command> [entry|exit] <message>
    description: sets the claim's entry/exit message
    permission: gpextras.command.setmessage
  gpsellclaim:
    usage: /<command> <saleprice>
    description: puts a claim up for sale.
    permission: gpextras.commands.sellclaim
  gpbuyclaim:
    usage: /<command>
    description: purchases a claim that's for sale.
    permission: gpextras.commands.buyclaim
  gprentclaim:
    usage: /<command>
    description: rent a claim that's for rent.
    permission: gpextras.commands.rentclaim
  gpsetrent:
      usage: /<command>
      description: set the rent price/duration for a claim
      permission: gpextras.commands.setrent

permissions:
  gpextras.commands.sellclaim:
    default: op
  gpextras.commands.buyclaim:
    default: op
  gpextras.flag.mobspawns:
    default: op
  gpextras.flag.pvp:
    default: op
  gpextras.command.setmessage:
    default: op
  gpextras.player:
    default: op
    children:
      gpextras.command.setmessage: true
      gpextras.command.sellclaim: true
      gpextras.command.buyclaim: true
      gpextras.flag.mobspawns: true
      gpextras.flag.pvp: true

  gpextras.admin:
    default: op
    children:
      gpextras.player: true
      gpextras.flag.hunger: true

